# Generated by Django 4.1.7 on 2023-02-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0003_alter_articulo_idarticulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='idArticulo',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='idCategoria',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='documento',
            field=models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='documento'),
        ),
    ]
