# Generated by Django 4.1.7 on 2023-02-28 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0005_alter_empleado_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_has_empleado',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventario.empleado'),
        ),
        migrations.AlterField(
            model_name='articulo_has_empleado',
            name='idArticulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventario.articulo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='idEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventario.empresa'),
        ),
    ]
